import { useRef, useState } from "react";
import { Image, Loader2, Send, X } from "lucide-react";
import toast from "react-hot-toast";
import { useChatStore } from "../store/useChatStore";

const MessageInput = () => {
  const [text, setText] = useState(""); const [imagePreview, setImagePreview] = useState(null); const [isSending, setIsSending] = useState(false); const fileInputRef = useRef(null); const { sendMessage } = useChatStore();
  const handleImageChange = (event) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) { toast.error("Please select an image file"); event.target.value = ""; return; } const reader = new FileReader(); reader.onloadend = () => setImagePreview(reader.result); reader.readAsDataURL(file); };
  const removeImage = () => { setImagePreview(null); if (fileInputRef.current) fileInputRef.current.value = ""; };
  const handleSendMessage = async (event) => { event.preventDefault(); if ((!text.trim() && !imagePreview) || isSending) return; setIsSending(true); await sendMessage({ text: text.trim(), image: imagePreview }); setText(""); removeImage(); setIsSending(false); };
  return <div className="shrink-0 border-t border-base-300 bg-base-100 px-3 py-3 sm:px-5">{imagePreview && <div className="mx-auto mb-3 max-w-4xl"><div className="relative inline-block"><img src={imagePreview} alt="Attachment preview" className="size-20 rounded-xl border border-base-300 object-cover" /><button onClick={removeImage} className="btn btn-circle btn-xs absolute -right-2 -top-2 border border-base-300 bg-base-100" type="button" aria-label="Remove image"><X className="size-3" /></button></div></div>}<form onSubmit={handleSendMessage} className="mx-auto flex max-w-4xl items-center gap-2"><input type="file" accept="image/*" className="hidden" ref={fileInputRef} onChange={handleImageChange} /><button type="button" className={`btn btn-ghost btn-square btn-sm sm:btn-md ${imagePreview ? "text-primary" : ""}`} onClick={() => fileInputRef.current?.click()} aria-label="Add image" disabled={isSending}><Image className="size-5" /></button><input type="text" className="input input-bordered h-11 min-w-0 flex-1 rounded-xl bg-base-100 px-4" placeholder="Write a message" value={text} onChange={(event) => setText(event.target.value)} disabled={isSending} /><button type="submit" className="btn btn-primary btn-square h-11 min-h-11 rounded-xl" disabled={(!text.trim() && !imagePreview) || isSending} aria-label="Send message">{isSending ? <Loader2 className="size-5 animate-spin" /> : <Send className="size-5" />}</button></form></div>;
};
export default MessageInput;
